### ISSUE TITLE
1.2.0カバレッジ

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#325]
20191104以降の未解決バグ:
- [x] #264 
- [x] #265 
- [ ] 整地量のバーが2本表示される [図](https://gyazo.com/bf8cbb2d428a5250981cd9f8791acfb4) reported by AnAnzu246Zk
- [ ] 整地量バーを非表示にした後再表示するとマナバーが上にくる (リログで治る)
- [ ] #262
- [x] #294 
- [x] 本番環境におい実績二つ名システム実績「記念日」の次ページへを無限にクリックできる(実績の以降は空っぽのメニューがある) reported by AnAnzu246Zk
- [x] #235 
- [x] ~~"幸運の申し子"が解除されない？ [未検証]~~
(EDIT:解除されました)
- [x] ~~Mebiusの挙動がおかしい。(再現性確認なし)
1.Mebiusが1回に2度発言してくる。
2.Mebiusを被ってもいないのに発言してくる。~~
(EDIT: 再現できず。とりあえずresolvedとする。)
- [x] 頭出すとき、名前が全部小文字になってるせい(かわからないけど)で頭のスキンがデフォルト(スティーブ)のままになる　reported by TeamMegumin (wontfix: 多分スキン読み込みのAPI制限などによる一時的なもの)
- [x] #318 
- [x] ~~ランキング、一括クラフトのページ飛びが機能していない [動画](https://youtu.be/YKoJOkCmQjo) reported  by Rem_MineZero_000
↑ 追記：実績・二つ名システム、投票ptメニュー、パッシブ・アクティブスキルブックの移動も作動してなかったです~~
- [x] ~~(EDIT:Scala-ize後｜一括クラフトの「ホームに戻る」ボタンだけ機能しない)~~
- [ ] グリッド式保護で自分がいるグリッドが保護に含まれない
(EDIT:本番環境でのバグに移動させた)
(EDIT: #297 で未済なものを移動)

**Comment by karayuumac** [comment]
本番環境的用後のバグ

- [ ] 整地スキルのエフェクト、アイスのエフェクト使用時、ブロックが一度氷塊に変わったあと、破壊されるという従来の仕様の通りに動作せず、色のついたエフェクトのみになっている。
- [ ] ガチャ券がおけてうんちゃまのあたまになる(ガチャが引けない)
- [ ] 棒メニューの ホームへ の部分を押した際、アイテム枠のサイズが同じだった際、ガチャ券が取り出される
- [ ] インベントリ共有でアイテムが取り出せない（収納はできる）
https://cdn.discordapp.com/attachments/640908643109437440/640908655138439169/unknown.png
- [ ] ロビーサーバーへ移動が未知のコマンド
- [ ] グリッド式保護作成画面が開けない
- [ ] 実績システム内の一部のメニューでアイテムが取得できる(岩盤が入手できてしまう)
- [ ] 一括クラフトの「ホームへ」が機能しない
- [ ] 整地ランキング、特殊カテゴリの3つ、実装されていない項目以外でアイテムが取得できてしまう

**Comment by karayuumac** [comment]
Not critical
- [ ] MineStackにおいて、アイテムがない時とある時の音が違ったはずが、現在ではない時に無音になってしまっている

**Comment by soundofhorizon** [comment]
#318
解決していない気がします

**Comment by soundofhorizon** [comment]
マナ消費量バグ
連爆系
トムボウイ　本来28　現在9or10
サンダーストーム　本来65　現在9or10?
スターライトブレーカー　本来90　現在30or31?
アースディバイド　本来185　現在37or38?
ヘヴンゲイボルグ　本来330　現在110or111?
ディシジョン　本来480　現在68or69？

検証法：隙間ない石の塊を作ってそれを壊す

何回かやった平均で入力
