### ISSUE TITLE
Redmine承認済みチケットカバレッジ

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/SeichiAssist#369]
[承認済みチケット](https://redmine.seichi.click/projects/idea/issues?utf8=✓&set_filter=1&f[]=status_id&op[status_id]=%3D&v[status_id][]=17&f[]=tracker_id&op[tracker_id]=%3D&v[tracker_id][]=19&f[]=&c[]=tracker&c[]=status&c[]=priority&c[]=subject&c[]=assigned_to&c[]=updated_on&c[]=due_date&c[]=parent&group_by=&t[]=)から。
参照: [GitHub上に存在する承認済みissue](https://github.com/GiganticMinecraft/SeichiAssist/issues?q=is:issue+is:open+sort:updated-desc+label:%22Status/Idea:+Accepted%E2%9C%85%22)
## 一覧
- [x] #678
- [x] #677
- [ ] #676
- [ ] #675
- [x] #674
- [ ] #688 
- [x] #689 
- [ ] [2505: Minestack内にあるアイテム（名義なし）の取引システム](https://redmine.seichi.click/issues/2505)
  - → #620 
- [x] [8237: 採掘速度上昇レベルの全鯖共通化](https://redmine.seichi.click/issues/8237)
  - → #621  
- [x] [8109: 鉄のトラップドアの開閉を動力無しでできるようにする](https://redmine.seichi.click/issues/8109)
  - → #622 
- [ ] [7586: 景観評価システム](https://redmine.seichi.click/7586)
  - → #500
- [x] [7423: 一括クラフトの追加](https://redmine.seichi.click/issues/7423)
  - → #605 
- [ ] [6395: Tipsを非表示にできるようにする](https://redmine.seichi.click/issues/6395)
  - 備考: 非公式Modあり
- [ ] [6372: MineStackにエンドストーンレンガ、プルプァブロック、柱状プルプァブロック、プルプァハーフ、プルプァ階段、エンドロッド、エンダーチェスト、ネザーレンガフェンス、ネザーレンガ階段を追加](https://redmine.seichi.click/issues/6372)
  - [x] エンドストーンレンガ
  - [x] プルプァ
  - [x] 柱状プルプァ
  - [x] プルプァハーフ
  - [x] プルプァ階段
  - [x] エンドロッド
  - [ ] エンダーチェスト
  - [x] ネザーレンガフェンス
  - [x] ネザーレンガ階段
- [ ] [4722: MineStackに堅焼き粘土全色、交換券を追加](https://redmine.seichi.click/issues/4722)
  - [x] 堅焼き粘土全色
  - [ ] 交換券
- [ ] [4189: ガチャ券を万単位で引ける機能](https://redmine.seichi.click/issues/4189)
  - →#281
- [x] [4159: GTゲットメッセージを無効化](https://redmine.seichi.click/issues/4159)
- [x] [3815: ホームポイントの増加](https://redmine.seichi.click/issues/3815)
- [ ] [3359: 整地ワールドの岩盤をフラットにする](https://redmine.seichi.click/issues/3359)
  - 備考: カスタムワールドジェネレーターをコード内で定義する必要あり
- [ ] [3241: 自分が整地できるY座標の制限](https://redmine.seichi.click/issues/3241)
  - →#727
- [ ] [2971: WorldEditのcopyみたいなことをマインスタックから消費して行う](https://redmine.seichi.click/issues/2971)
  - 備考: 先行議論あり
- [ ] [2044: 低いレベル層でガチャ券をレベルアップごとにプレゼント](https://redmine.seichi.click/issues/2044)
- [ ] [1736: ガチャ景品UUID管理](https://redmine.seichi.click/issues/1736)
  - → #82
- [ ] [1094: 仮想的な足場](https://redmine.seichi.click/issues/1094)
- [ ] [1061: テンポラリなマナ最大値増加](https://redmine.seichi.click/issues/1061)
- [ ] [1001/1002: 期間限定で特定のバイオームに対して整地量のバフ](https://redmine.seichi.click/issues/1001)
  - 備考: 現在ではバフはイベントごとに設定される
- [ ] [983: 連続投票の二つ名の追加](https://redmine.seichi.click/issues/983)
- [ ] [967: アイテム名にちなんだ二つ名の追加](https://redmine.seichi.click/issues/967)
- [ ] [965: 二つ名の組み合わせを記憶しておく/ランダムに組み合わせる](https://redmine.seichi.click/issues/965)
- [ ] [705: エンドラの頭をガチャ景品として出す](https://redmine.seichi.click/issues/705)
- [x] [8050: 整地ランキングにスターレベルを追加する](https://redmine.seichi.click/issues/8050)
  - → #597 で実装済み
- [x] [8046: 溶岩バケツを一括クラフトに追加する](https://redmine.seichi.click/issues/8046)
  - → #515  で実装済
- [x] [7616/7421: ガチャ券の結果を1行にする](https://redmine.seichi.click/issues/7421)
  - → #472 → #502 で実装済
- [x] [7359: 二つ名の中パーツに「か」を追加](https://redmine.seichi.click/issues/7359) 
- [x] [7255: 運営からのガチャ券のクールダウン短縮](https://redmine.seichi.click/issues/7255) 
- [x] [7165: /mapコマンドの追加](https://redmine.seichi.click/issues/7165) 
  - → #314 で実装済
- [x] [7137/5369: スターレベルが上がるときにﾑﾑｯwwwを追加する](https://redmine.seichi.click/issues/7137) 
  - → #280 で実装済
- [x] [7105: Tipsからエンダードラゴンを削除](https://redmine.seichi.click/issues/7105)
- [x] [7050: 棒メニュー => サーバー選択画面でs8に移動したい](https://redmine.seichi.click/issues/7050)
- [x] [6953: 水色を青緑色に変更](https://redmine.seichi.click/issues/6953)
- [x] [6352/6266: 堅焼き粘土→テラコッタ](https://redmine.seichi.click/issues/6352)
- [x] [6045: MineStackに青いじゃがいもを追加](https://redmine.seichi.click/issues/6045)
- [x] [5940: MineStackに植木鉢、鉄柵を追加](https://redmine.seichi.click/issues/5940)
- [x] [5525: 妖精さんのいる時間を増減できるようにする](https://redmine.seichi.click/issues/5525)
- [x] [5402/4349: 30分ランキングに自身の整地量も追加する](https://redmine.seichi.click/issues/5402)
- [x] [5363: 凝固スキルをナーフ](https://redmine.seichi.click/issues/5363)
- [x] [5140: MineStackに看板、鉄格子、額縁、絵画、石レンガの階段、エンドクリスタル、ジュークボックス、金床、ウィザスケの頭、ブレイズパウダーを追加](https://redmine.seichi.click/issues/5140)
- [x] [5124/4328/1152/988: ガチャ景品を直接MineStackへ](https://redmine.seichi.click/issues/5124)
  - → #436 で実装済
- [x] [5106: 建築量に応じた実績](https://redmine.seichi.click/issues/5106)
- [x] [5006: フレキシブルな採掘速度上限](https://redmine.seichi.click/issues/5006)
- [x] [4731: 一括設置スキルの修正](https://redmine.seichi.click/issues/4731)
- [x] [4730: MineStackに石炭ブロックを追加](https://redmine.seichi.click/issues/4730)
- [x] [4687: ホームポイントの名前付け](https://redmine.seichi.click/issues/4687)
- [x] [4068: 一括破壊対象にスイカ、かぼちゃ、階段、ガラス、耕地、草の道、スポーンブロックを追加](https://redmine.seichi.click/issues/4068)
- [x] [4067/1096: MineStackで木の葉のレベルを下げる](https://redmine.seichi.click/issues/4067)
  - 備考: 現在すべてのレベルが1なので実質実装済み
- [x] [3653: AFKプレイヤーのFly消費経験値をゼロにする](https://redmine.seichi.click/issues/3653)
- [x] [2000: MineStackに整地ドロップをダイレクト格納](https://redmine.seichi.click/issues/2000)
- [x] [1644: スキルに焼石ハーフを追加](https://redmine.seichi.click/issues/1644)
- [x] [1009: スキル対象に耕地を追加](https://redmine.seichi.click/issues/1009)
- [x] [1004: スキル対象に草の道を追加](https://redmine.seichi.click/issues/1004)
- [x] [989: 氷結で蓮も回収できるようにする](https://redmine.seichi.click/issues/989)
- [x] [944: 凝固で整地量が増加するようにする](https://redmine.seichi.click/issues/944)
- [x] [903: 採掘速度上昇の内訳の切り捨て](https://redmine.seichi.click/issues/903)
  - 備考: IEEE 754
  - 備考: すでに内訳に少数が登場しないため実質実装済み
- [x] [856: Lv200以降のやりこみ要素](https://redmine.seichi.click/issues/856)
- [x] [855: 戦闘レベル](https://redmine.seichi.click/issues/855)
  - 備考: GiganticBerserkとして実装済み
- [x] [788: 一括クラフト: 砂岩→なめらかな砂岩](https://redmine.seichi.click/issues/788)

**Comment by soundofhorizon** [comment]
お疲れ様です。
855 -> Gigantic Berserkにて実装済み
903 -> 少数の概念はもう無いです
989 -> 実装済み
1001/1002 -> 各イベントについてという形で締結していそう
1004.1009.1644 -> 実装済み
3815 -> 現在ホームポイントは6つに増加している
4068.4687.4731.5140.5363.5525.6372-> 実装済み
6395 -> 非公式Modで片づけられているがそれでもいいのか
7105 -> 実装済み
7137/5369 -> 自分が実装したはず

以上よろしくお願いします

**Comment by KisaragiEffective** [comment]
@soundofhorizon 全件反映しました。ありがとうございました。

**Comment by soundofhorizon** [comment]
お疲れ様です。
856 -> スターレベルとして実装済み
5006, 5106 -> 実装済み

以上よろしくお願いいたします。

**Comment by KisaragiEffective** [comment]
@soundofhorizon 全件反映しました。ありがとうございました。

**Comment by KisaragiEffective** [comment]
unusable
